/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.cdrf.r9;

import com.beanit.jasn1.ber.types.BerInteger;

import java.math.BigInteger;


public class CallEventRecordType extends BerInteger {

	private static final long serialVersionUID = 1L;

	public CallEventRecordType() {
	}

	public CallEventRecordType(byte[] code) {
		super(code);
	}

	public CallEventRecordType(BigInteger value) {
		super(value);
	}

	public CallEventRecordType(long value) {
		super(value);
	}

}
