/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.cdrf.r9;

import com.beanit.jasn1.ber.types.BerOctetString;


public class CallReferenceNumber extends BerOctetString {

	private static final long serialVersionUID = 1L;

	public CallReferenceNumber() {
	}

	public CallReferenceNumber(byte[] value) {
		super(value);
	}

}
