/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.cdrf.r9;


public class CallingNumber extends BCDDirectoryNumber {

	private static final long serialVersionUID = 1L;

	public CallingNumber() {
	}

	public CallingNumber(byte[] value) {
		super(value);
	}

}
