/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.cdrf.r9;


public class CAMELAccessPointNameOI extends AccessPointNameOI {

	private static final long serialVersionUID = 1L;

	public CAMELAccessPointNameOI() {
	}

	public CAMELAccessPointNameOI(byte[] value) {
		super(value);
	}

}
