/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.cdrf.r9;


public class CAMELAccessPointNameNI extends AccessPointNameNI {

	private static final long serialVersionUID = 1L;

	public CAMELAccessPointNameNI() {
	}

	public CAMELAccessPointNameNI(byte[] value) {
		super(value);
	}

}
