/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.cdrf.r9;

import com.beanit.jasn1.ber.types.BerBoolean;


public class DynamicAddressFlag extends BerBoolean {

	private static final long serialVersionUID = 1L;

	public DynamicAddressFlag() {
	}

	public DynamicAddressFlag(byte[] code) {
		super(code);
	}

	public DynamicAddressFlag(boolean value) {
		super(value);
	}

}
