/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.cdrf.r9;


public class GSNAddress extends IPAddress {

	private static final long serialVersionUID = 1L;

	public GSNAddress() {
	}

	public GSNAddress(byte[] code) {
		super(code);
	}

}
