/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.cdrf.r9;


public class IMEI extends TBCDSTRING {

	private static final long serialVersionUID = 1L;

	public IMEI() {
	}

	public IMEI(byte[] value) {
		super(value);
	}

}
