/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.cdrf.r9;


public class IMSI extends TBCDSTRING {

	private static final long serialVersionUID = 1L;

	public IMSI() {
	}

	public IMSI(byte[] value) {
		super(value);
	}

}
