/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.cdrf.r9;


public class ISDNAddressString extends AddressString {

	private static final long serialVersionUID = 1L;

	public ISDNAddressString() {
	}

	public ISDNAddressString(byte[] value) {
		super(value);
	}

}
