/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.cdrf.r9;

import com.beanit.jasn1.ber.types.BerOctetString;


public class LCSPriority extends BerOctetString {

	private static final long serialVersionUID = 1L;

	public LCSPriority() {
	}

	public LCSPriority(byte[] value) {
		super(value);
	}

}
