/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.cdrf.r9;

import com.beanit.jasn1.ber.types.BerBitString;


public class LevelOfCAMELService extends BerBitString {

	private static final long serialVersionUID = 1L;

	public LevelOfCAMELService() {
	}

	public LevelOfCAMELService(byte[] code) {
		super(code);
	}

	public LevelOfCAMELService(byte[] value, int numBits) {
		super(value, numBits);
	}

	public LevelOfCAMELService(boolean[] value) {
		super(value);
	}

}
