/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.cdrf.r9;

import com.beanit.jasn1.ber.types.BerEnum;

import java.math.BigInteger;


public class MBMS2G3GIndicator extends BerEnum {

	private static final long serialVersionUID = 1L;

	public MBMS2G3GIndicator() {
	}

	public MBMS2G3GIndicator(byte[] code) {
		super(code);
	}

	public MBMS2G3GIndicator(BigInteger value) {
		super(value);
	}

	public MBMS2G3GIndicator(long value) {
		super(value);
	}

}
