/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.cdrf.r9;


public class MSISDN extends ISDNAddressString {

	private static final long serialVersionUID = 1L;

	public MSISDN() {
	}

	public MSISDN(byte[] value) {
		super(value);
	}

}
