/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.cdrf.r9;

import com.beanit.jasn1.ber.types.string.BerIA5String;


public class NodeID extends BerIA5String {

	private static final long serialVersionUID = 1L;

	public NodeID() {
	}

	public NodeID(byte[] value) {
		super(value);
	}

}
