/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.cdrf.r9;

import com.beanit.jasn1.ber.types.BerEnum;

import java.math.BigInteger;


public class NotificationToMSUser extends BerEnum {

	private static final long serialVersionUID = 1L;

	public NotificationToMSUser() {
	}

	public NotificationToMSUser(byte[] code) {
		super(code);
	}

	public NotificationToMSUser(BigInteger value) {
		super(value);
	}

	public NotificationToMSUser(long value) {
		super(value);
	}

}
