/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.cdrf.r9;


public class RecordingEntity extends AddressString {

	private static final long serialVersionUID = 1L;

	public RecordingEntity() {
	}

	public RecordingEntity(byte[] value) {
		super(value);
	}

}
