/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.cdrf.r9;

import com.beanit.jasn1.ber.types.BerEnum;

import java.math.BigInteger;


public class ServingNodeType extends BerEnum {

	private static final long serialVersionUID = 1L;

	public ServingNodeType() {
	}

	public ServingNodeType(byte[] code) {
		super(code);
	}

	public ServingNodeType(BigInteger value) {
		super(value);
	}

	public ServingNodeType(long value) {
		super(value);
	}

}
