/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.cdrf.r9;

import com.beanit.jasn1.ber.types.BerBoolean;


public class SGWChange extends BerBoolean {

	private static final long serialVersionUID = 1L;

	public SGWChange() {
	}

	public SGWChange(byte[] code) {
		super(code);
	}

	public SGWChange(boolean value) {
		super(value);
	}

}
