/**
 * This class file was automatically generated by jASN1 (http://www.beanit.com)
 */

package com.beanit.jasn1.compiler.cdrf.r9;


public class SMSResult extends Diagnostics {

	private static final long serialVersionUID = 1L;

	public SMSResult() {
	}

	public SMSResult(byte[] code) {
		super(code);
	}

}
